In [23]:
#載入StandardScaler

In [24]:
from sklearn.preprocessing import StandardScaler

In [25]:
scaler = StandardScaler()

In [26]:
data = [[0, 0], [0, 0], [1, 1], [1, 1]]

In [27]:
scaler.fit(data)

StandardScaler(copy=True, with_mean=True, with_std=True)

In [28]:
scaler.mean_

array([0.5, 0.5])

In [29]:
scaler.transform(data)

array([[-1., -1.],
       [-1., -1.],
       [ 1.,  1.],
       [ 1.,  1.]])

In [30]:
scaler.transform([[2, 2]])

array([[3., 3.]])

In [31]:
#將mystandardscale做fit、transform、fit_transform

In [32]:

class mystandardscaler:
    def __init__(self):
        self.mean_ = None
        self.scale_ = None
        
    def fit(self, data):
        self.mean_ = np.mean(data, axis = 0)
        self.scale_ = np.std(data, axis = 0)
        
    def transform(self, data):
        new_data = (np.array(data) - self.mean_)/self.scale_
        return new_data
    
    def fit_transform(self, data):
        self.fit(data)
        return self.transform(data)

In [33]:
mystandardscaler = mystandardscaler()

In [34]:
import numpy as np

In [35]:
mystandardscaler.fit(data)

In [36]:
mystandardscaler.mean_

array([0.5, 0.5])

In [37]:
mystandardscaler.scale_

array([0.5, 0.5])

In [38]:
mystandardscaler.transform(data)

array([[-1., -1.],
       [-1., -1.],
       [ 1.,  1.],
       [ 1.,  1.]])

In [39]:
mystandardscaler_new=mystandardscaler

In [40]:
mystandardscaler_new.fit_transform(data)

array([[-1., -1.],
       [-1., -1.],
       [ 1.,  1.],
       [ 1.,  1.]])